const conditionTranslations = {
  "Rain showers": { pt:"Pancadas de chuva", es:"Chubascos", fr:"Averses", de:"Regenschauer", it:"Rovesci di pioggia", ru:"Ливневые дожди", zh:"阵雨", ja:"にわか雨", ar:"زخات مطر", hi:"बारिश की फुहारें" },
  "Light rain": { pt:"Chuva leve", es:"Lluvia ligera", fr:"Pluie légère", de:"Leichter Regen", it:"Pioggia leggera", ru:"Небольшой дождь", zh:"小雨", ja:"小雨", ar:"مطر خفيف", hi:"हल्की बारिश" },
  "Moderate rain": { pt:"Chuva moderada", es:"Lluvia moderada", fr:"Pluie modérée", de:"Mäßiger Regen", it:"Pioggia moderata", ru:"Умеренный дождь", zh:"中雨", ja:"適度な雨", ar:"مطر معتدل", hi:"मध्यम बारिश" },
  "Heavy rain": { pt:"Chuva forte", es:"Lluvia intensa", fr:"Forte pluie", de:"Starker Regen", it:"Pioggia intensa", ru:"Сильный дождь", zh:"大雨", ja:"強い雨", ar:"مطر غزير", hi:"तेज़ बारिश" },
  "Partly cloudy": { pt:"Parcialmente nublado", es:"Parcialmente nublado", fr:"Partiellement nuageux", de:"Teilweise bewölkt", it:"Parzialmente nuvoloso", ru:"Переменная облачность", zh:"局部多云", ja:"ところにより曇り", ar:"غائم جزئياً", hi:"आंशिक बादल" },
  "Cloudy": { pt:"Nublado", es:"Nublado", fr:"Nuageux", de:"Bewölkt", it:"Nuvoloso", ru:"Облачно", zh:"多云", ja:"曇り", ar:"غائم", hi:"बादल छाए हुए" },
  "Clear sky": { pt:"Céu limpo", es:"Cielo despejado", fr:"Ciel dégagé", de:"Klarer Himmel", it:"Cielo sereno", ru:"Ясное небо", zh:"晴朗", ja:"快晴", ar:"سماء صافية", hi:"साफ आसमान" },
  "Sunny": { pt:"Ensolarado", es:"Soleado", fr:"Ensoleillé", de:"Sonnig", it:"Soleggiato", ru:"Солнечно", zh:"晴天", ja:"晴れ", ar:"مشمس", hi:"धूप" }
};

const insightTranslations = {
  "High rainfall may delay field operations and increase disease pressure.": { pt:"Chuvas intensas podem atrasar as operações no campo e aumentar a pressão de doenças.", es:"Las lluvias intensas pueden retrasar las operaciones en el campo y aumentar la presión de enfermedades.", fr:"De fortes pluies peuvent retarder les opérations au champ et augmenter la pression des maladies.", de:"Starke Niederschläge können Feldarbeiten verzögern und den Krankheitsdruck erhöhen.", it:"Piogge intense possono ritardare le operazioni in campo e aumentare la pressione delle malattie.", ru:"Сильные осадки могут задержать полевые работы и повысить риск заболеваний.", zh:"强降雨可能会延迟田间作业并增加病害压力。", ja:"強い降雨は圃場作業を遅らせ、病害圧を高める可能性があります。", ar:"قد تؤدي الأمطار الغزيرة إلى تأخير العمليات الحقلية وزيادة ضغط الأمراض.", hi:"अधिक वर्षा खेत के काम में देरी कर सकती है और रोग के दबाव को बढ़ा सकती है।" },
  "High humidity can elevate fungal disease risk in sensitive crops.": { pt:"A alta umidade pode elevar o risco de doenças fúngicas em culturas sensíveis.", es:"La alta humedad puede elevar el riesgo de enfermedades fúngicas en cultivos sensibles.", fr:"Une humidité élevée peut augmenter le risque de maladies fongiques dans les cultures sensibles.", de:"Hohe Luftfeuchtigkeit kann das Risiko von Pilzkrankheiten bei empfindlichen Kulturen erhöhen.", it:"L'elevata umidità può aumentare il rischio di malattie fungine nelle colture sensibili.", ru:"Высокая влажность может повысить риск грибковых заболеваний у чувствительных культур.", zh:"高湿度会增加敏感作物真菌病害的风险。", ja:"高湿度は感受性の高い作物で真菌病のリスクを高める可能性があります。", ar:"يمكن أن تؤدي الرطوبة العالية إلى زيادة خطر الأمراض الفطرية في المحاصيل الحساسة.", hi:"अधिक आर्द्रता संवेदनशील फसलों में फफूंद रोग का जोखिम बढ़ा सकती है।" },
  "Conditions look favorable for many field activities and general crop development.": { pt:"As condições parecem favoráveis para muitas atividades no campo e para o desenvolvimento geral das culturas.", es:"Las condiciones parecen favorables para muchas actividades de campo y el desarrollo general de los cultivos.", fr:"Les conditions semblent favorables à de nombreuses activités au champ et au développement général des cultures.", de:"Die Bedingungen wirken günstig für viele Feldarbeiten und die allgemeine Entwicklung der Kulturen.", it:"Le condizioni sembrano favorevoli per molte attività in campo e per lo sviluppo generale delle colture.", ru:"Условия выглядят благоприятными для многих полевых работ и общего развития культур.", zh:"这些条件看起来有利于许多田间活动和作物的整体生长。", ja:"これらの条件は、多くの圃場作業や作物全体の生育に有利に見えます。", ar:"تبدو الظروف مناسبة للعديد من الأنشطة الحقلية وللتطور العام للمحاصيل.", hi:"स्थितियाँ कई खेत कार्यों और फसलों के सामान्य विकास के लिए अनुकूल लगती हैं।" },
  "Strong winds may affect spraying conditions and plant stress.": { pt:"Ventos fortes podem afetar as condições de pulverização e aumentar o estresse das plantas.", es:"Los vientos fuertes pueden afectar las condiciones de pulverización y aumentar el estrés de las plantas.", fr:"Des vents forts peuvent affecter les conditions de pulvérisation et accroître le stress des plantes.", de:"Starke Winde können die Spritzbedingungen beeinflussen und den Pflanzenstress erhöhen.", it:"Venti forti possono influenzare le condizioni di irrorazione e aumentare lo stress delle piante.", ru:"Сильный ветер может ухудшить условия опрыскивания и усилить стресс растений.", zh:"强风可能会影响喷洒条件并增加植物压力。", ja:"強風は散布条件に影響し、植物ストレスを高める可能性があります。", ar:"قد تؤثر الرياح القوية على ظروف الرش وتزيد من إجهاد النباتات.", hi:"तेज़ हवाएँ छिड़काव की स्थिति को प्रभावित कर सकती हैं और पौधों का तनाव बढ़ा सकती हैं।" },
  "Monitor field conditions closely and combine this data with local crop-specific recommendations.": { pt:"Monitore atentamente as condições do campo e combine esses dados com recomendações locais específicas para cada cultura.", es:"Supervise de cerca las condiciones del campo y combine estos datos con recomendaciones locales específicas para cada cultivo.", fr:"Surveillez attentivement les conditions du champ et combinez ces données avec des recommandations locales propres à chaque culture.", de:"Beobachten Sie die Feldbedingungen genau und kombinieren Sie diese Daten mit lokalen, kulturspezifischen Empfehlungen.", it:"Monitora attentamente le condizioni del campo e combina questi dati con raccomandazioni locali specifiche per coltura.", ru:"Внимательно следите за условиями в поле и сочетайте эти данные с местными рекомендациями по конкретным культурам.", zh:"请密切监测田间状况，并将这些数据与当地作物的具体建议结合使用。", ja:"圃場条件を注意深く確認し、これらのデータを地域ごとの作物別推奨事項と組み合わせてください。", ar:"راقب ظروف الحقل عن كثب وادمج هذه البيانات مع التوصيات المحلية الخاصة بكل محصول.", hi:"खेत की स्थितियों पर ध्यान से नज़र रखें और इस डेटा को स्थानीय फसल-विशिष्ट सिफारिशों के साथ मिलाएँ।" }
};

function translateValue(value, language, map) {
  if (language === "en") return value;
  return map[value]?.[language] || value;
}

export function translateSummaryAndInsight(item, language) {
  return {
    summary: translateValue(item.summary, language, conditionTranslations),
    insight: translateValue(item.insight, language, insightTranslations)
  };
}
